### ISSUE TITLE
Roaster Sidebar Broken From Session

### ISSUE THREAD

**Issue by jonnykry** [jonnykry/expresso#22]
# Issue

If you log in naturally, you can use the Roaster sidebar.  If you refresh the page, you're still authenticated due to the session token, but we don't have access to the user's roaster account ID anymore.  That's because this was stored in the app state after the user logs in.

There's a few different ways we can handle this.  We could create a method to get a user's roaster via token, or we need to store the roaster ID in LocalStorage, or ... (tbd)

I'm working on a couple other things right now, so I just wanted to create a ticket as to not forget about this.

**Comment by jakelong95** [comment]
Could we just dispatch an action whenever the user goes to the roaster account page that gets the roaster's information?

**Comment by jonnykry** [comment]
Spoke on Slack w/ @jakelong95, he's fixing this by setting the `userId` in `localStorage` and fetching the user information in `App.js`.
