### ISSUE TITLE
Infinite Scroll and/or Pagination

### ISSUE THREAD

**Issue by jonnykry** [jonnykry/expresso#24]
# Issue

If I understand correctly - as it currently is implemented - we just continuously fetch items until there are no more items to fetch.

Imo, we should use an infinite scroll technique that takes advantage of browser scroll to load items when we hit the bottom of the page.

There's a lot of different ways to handle this, we should discuss our favorite and go for it.

Discuss!

**Comment by ghmeier** [comment]
That's the correct understanding. I personally don't have a preference either way. Hopefully it's something we could contain in a single component that's easy to add to all our pages.

**Comment by jonnykry** [comment]
Agreed.  I think we're sort of already close to the infinite scroll type of implementation.  I'm in favor of going for that route!

Also, we could even use (or use the same technique as) this (https://github.com/CassetteRocks/react-infinite-scroller).

**Comment by ghmeier** [comment]
solid. seems like we'd just have to add a check for whether or not we're at the end of the screen before we fetch more, and then restart fetching if we reach the bottom

**Comment by jonnykry** [comment]
Yup!

I'll open this up to anyone who wants to pick it up, but I can also pick it up since it was the next portion of the bean item list I was going to work on.

**Comment by ghmeier** [comment]
I'll pick it up

**Comment by jonnykry** [comment]
Fixed by https://github.com/jonnykry/expresso/pull/30
