### ISSUE TITLE
Newly registered users are experiencing authentication issues on dashboard

### ISSUE THREAD

**Issue by jonnykry** [jonnykry/expresso#32]
# Issue

See title.

### Steps to Reproduce

- Register a new user on `/register`
- Once in the dashboard, you'll notice token/auth problems

**Comment by ghmeier** [comment]
We're getting a 500 error and this response:
```
{"data":{"id":"","passHash":"g","firstName":"G","lastName":"M","email":"g@g.g","phone":"1","addressLine1":"g","addressLine2":"","addressCity":"g","addressState":"AL","addressZip":"10000","addressCountry":"United States","roasterId":"","profileUrl":""},"message":"Error 1136: Column count doesn't match value count at row 1","success":false}
```

Server logs look like this:
```
[GIN] 2017/03/22 - 01:21:55 | 500 |  154.518242ms | 173.28.184.239 |   POST    /api/user
[GIN] 2017/03/22 - 01:22:07 | 401 |    3.608215ms | 173.28.184.239 |   GET     /api/user
ERROR: unable to prepare query INSERT INTO user (id, passHash, firstName, lastName, email, phone, addressLine1, addressLine2, addressCity, addressState, addressZip, addressCountry, roasterId, profileUrl) VALUE (?,?,?,?,?,?,?,?,?,?,?,?,?)
```

I think I messed this up when I added profile pictures. Woops.

**Comment by ghmeier** [comment]
So there were two issues: 
1. the insert query
2. calls through the bloodlines gateway weren't finding a JWT token and were returning an invalid response. 

2 seems like a deeper issue with the gateways that i'll inspect more, but I have a quick hot-fix that looks to fix the issue.

**Comment by ghmeier** [comment]
Update, it's not fixed yet. I'll look tomorrow.

**Comment by ghmeier** [comment]
Fixed in https://github.com/jonnykry/expresso/pull/35
