### ISSUE TITLE
Implement 404 and other error handling pages

### ISSUE THREAD

**Issue by jonnykry** [jonnykry/expresso#39]
# Issue

If you try to go to a page that doesn't exist (or some other error) we should provide a pretty error page with a way to get back.

**Comment by ghmeier** [comment]
Added a 404 page, whatcha think (the link is `/dashboard`)? 

![404](https://cloud.githubusercontent.com/assets/5702686/24720760/2fdbd2b8-1a0c-11e7-94e8-96602e83bc91.png)
