### ISSUE TITLE
Get shipping label for orders

### ISSUE THREAD

**Issue by ghmeier** [jonnykry/expresso#48]
Roasters should be able to download pdf shipping labels for printing of orders.

**Comment by jonnykry** [comment]
Are we wanting to use Shippo for this?  Looks like they have an API for it.  I'm thinking of how to do this and am at a loss outside of using a pre-existing API due to time constraints.

https://goshippo.com/docs/single-call

**Comment by ghmeier** [comment]
Yep. I feel like an external api was always the plan.

**Comment by jonnykry** [comment]
My opinion is that this should exist on the Subscription object and be handled on the backend when a new Subscription is created.  I see the shipping label attached to Roaster Subscriptions on the dashboard, and they can click the link or image to open up the image and download it.

Open to differing opinions here, lemme know!

**Comment by yuderekyu** [comment]
https://github.com/lcollin/warehouse/issues/6

**Comment by yuderekyu** [comment]
Implemented in https://github.com/lcollin/warehouse/pull/9
