### ISSUE TITLE
Roaster "Packaging Info" Page

### ISSUE THREAD

**Issue by jonnykry** [jonnykry/expresso#65]
# Issue

We need a page for roasters to submit Packaging Info for @yuderekyu to hook up with Shippo shipping labels.  This page will offer a form to submit information up to Warehouse and receive/display a downloadable shipping label.

Currently, I think this will hook into the Orders that @lcollin is working on.

**Comment by yuderekyu** [comment]
**Packaging info** consists of: Quantity, OzInBag, Length, Width, Height, Distance Unit, and Mass Unit.
 
Shippo's choices for **Distance Units** are millimeter, centimeter, meter, inch, foot, yard.
**Mass Units** are gram, kilogram, ounce, and pound.

**Comment by yuderekyu** [comment]
There will be two urls returned: `labelUrl` represents the link to the shipment label. `trackingUrl` represents the link view the status of the shipment and the respective delivery service.
