### ISSUE TITLE
Default Bean Item (or otherwise) Image

### ISSUE THREAD

**Issue by jonnykry** [jonnykry/expresso#73]
# Issue

We need a default image hosted on AWS or something for when we don't have an image.

**Comment by ghmeier** [comment]
Try dis? 

![](https://s3.amazonaws.com/warehouse-profile/coffee_beans.png)

[https://s3.amazonaws.com/warehouse-profile/coffee_beans.png](https://s3.amazonaws.com/warehouse-profile/coffee_beans.png)
