### ISSUE TITLE
Home and About don't scroll

### ISSUE THREAD

**Issue by ghmeier** [jonnykry/expresso#82]
The home page and about page don't scroll :1234:

**Comment by jonnykry** [comment]
None of the pages that stem from `/` will scroll (this includes About, which we haven't implemented) unless we've fixed to add the `overflow` and `height: 100%`'s.  Not sure why.

Adding About to this.

**Comment by ghmeier** [comment]
Did this get finished w/ latest pr?

**Comment by jonnykry** [comment]
Fixed https://github.com/jonnykry/expresso/pull/83
